use novatech;

INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GilesPhillips@toto.com', '1' ,'Giles', 'Phillips', 2, '52 Rue  du radin 92950', '1988-11-20', 'no=uQVYR5M%kv@IB7HVC');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PhyllisHuffman@boomfaya.com', '2' ,'Phyllis', 'Huffman', 2, '23 Rue  des putois 92742', '1988-6-14', 'EKo+t6auem3QIn}]%Zb*');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CameranReid@tata.com', '3' ,'Cameran', 'Reid', 1, '51 Rue  des temps 92276', '1988-12-17', '{f*P6*hn+qkDg1Gg3_YO');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ParkBoone@zetrov.ru', '4' ,'Park', 'Boone', 2, '90 Rue  de la fuerca 92426', '1986-2-1', 'fpUi)myKzA5HtAYy+SMm');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GrahamNell@netflix.com', '5' ,'Graham', 'Nell', 2, '2 Rue  des raclettes 92916', '1995-4-19', '$WF+1K{&UP+s(gJ$_=qN');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('OwensHolcomb@toto.com', '6' ,'Owens', 'Holcomb', 2, '50 Rue  de la poucave  92455', '1994-1-7', 'X_L]P=k!!XZd9ZnxI4Bp');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('AllenStanley@lefou.com', '7' ,'Allen', 'Stanley', 1, '94 Rue  des raclettes 92434', '1984-1-26', '{SgnHt6QH}wZUxisRnfa');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WareDillon@tacos.fr', '8' ,'Ware', 'Dillon', 2, '27 Rue  de la fuerca 92055', '1984-4-26', 'z@)T!9=?PmaHrYSm?)E2');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CantuGriffith@tata.com', '9' ,'Cantu', 'Griffith', 2, '57 Rue  de la fuerca 92949', '1996-5-8', 'OArQV]KvX2xZT@G$Bdy4');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('JimenezJoyner@zakahev.ru', '10' ,'Jimenez', 'Joyner', 1, '68 Rue  des salades de fruits 92221', '1988-10-7', 'Ip0}9Y8p*}OzL@wc7G5_');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DillonFlorence@zetrov.ru', '11' ,'Dillon', 'Florence', 2, '21 Rue  du radin 92957', '1996-9-22', '+T-e9Fz2uj[n&sSBlGW?');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('XanderMaggie@yahoo.fr', '12' ,'Xander', 'Maggie', 2, '2 Rue  des salades de fruits 92413', '1991-8-27', 'Y3bsz{kx7)PqJ+Y@u{}&');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PriscillaHebert@tacos.fr', '13' ,'Priscilla', 'Hebert', 1, '41 Rue  du radin 92452', '1976-6-11', 'e=%QaN+!k]cLt9F{o?sG');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CobyTamara@oracle.com', '14' ,'Coby', 'Tamara', 1, '23 Rue  des fous 92075', '1986-1-6', 'FOVP+(WtP79J8mkEqz4u');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('NicholsCastor@boomfaya.com', '15' ,'Nichols', 'Castor', 1, '11 Rue  du radin 92433', '1996-6-26', 'u5}va%*DDN5%WtqfE[G@');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('MaxwellMaggie@zumba.fr', '16' ,'Maxwell', 'Maggie', 2, '22 Rue  de la fete 92968', '1977-1-4', '+$lmq!O]ZTbUswm!U4S]');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GradyJoyner@tata.com', '17' ,'Grady', 'Joyner', 1, '67 Rue  des fous 92099', '1995-6-12', 'HfgYTO+mQVCBC1S&I_QS');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DustinMedge@boomfaya.com', '18' ,'Dustin', 'Medge', 2, '13 Rue  des putois 92517', '1989-10-8', 'p32]!dPR[m7ZTpTks-SU');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('FaithDodson@yopmail.com', '19' ,'Faith', 'Dodson', 1, '75 Rue  du radin 92990', '1993-5-4', '(?0kyuwUP=gnQ_PbFGL_');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DanielsCantu@yopmail.com', '20' ,'Daniels', 'Cantu', 2, '28 Rue  de la fuerca 92787', '1984-3-2', 'n}&c5y{HK8e@(Ad0irjq');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('RyleeIsadora@bestmail.com', '21' ,'Rylee', 'Isadora', 1, '72 Rue  de la poucave  92657', '1983-5-4', 'ard!LIn!E$tU=9O(x_Eh');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BasilMadison@yopmail.com', '22' ,'Basil', 'Madison', 1, '46 Rue  des raclettes 92637', '1979-9-7', '$N?[[ZFo?xC*M&{VBAKc');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('AnjolieHays@zumba.fr', '23' ,'Anjolie', 'Hays', 2, '2 Rue  de la poucave  92322', '1994-12-27', 'g+9!Jba{c7+0KA+u5HhN');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GriffithDana@email.fr', '24' ,'Griffith', 'Dana', 1, '82 Rue  du radin 92532', '1976-6-6', 'Xr2O}eGw5PS7gK_A}[BF');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DaleQuentin@tacos.fr', '25' ,'Dale', 'Quentin', 1, '92 Rue  du moulin 92838', '1983-7-13', 'q6ZsAj]VwTF!eYugK([e');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('JohnstonWatkins@email.fr', '26' ,'Johnston', 'Watkins', 1, '89 Rue  du radin 92357', '1982-11-27', 'mV}mBiMLg%3dk8e}*(hT');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ZeusKarina@cocorico.com', '27' ,'Zeus', 'Karina', 2, '11 Rue  de la fuerca 92585', '1975-7-10', 'nS]pNu(7VAe_xDN)n[lg');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('SybillPruitt@tata.com', '28' ,'Sybill', 'Pruitt', 1, '65 Rue  du moulin 92321', '1996-2-14', 'bX(XeL&K]pZy9LAXIh9+');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('StacyJackson@oracle.com', '29' ,'Stacy', 'Jackson', 2, '67 Rue  des salades de fruits 92702', '1980-12-16', 'z@6ySEc[MGP1gsm7czeA');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('XanderGiles@bestmail.com', '30' ,'Xander', 'Giles', 1, '51 Rue  du feu 92022', '2000-4-4', '[uNPRo{SXt_aGGwN99@k');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ReedLambert@yopmail.com', '31' ,'Reed', 'Lambert', 2, '65 Rue  de la fete 92058', '1985-5-13', 'G@@q1=E)fMemAt02*B0p');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('OdomEstrada@tacos.fr', '32' ,'Odom', 'Estrada', 2, '46 Rue  des fous 92456', '1999-4-3', 'h2P+A_5Z?uYPl]Z+S0ta');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('HebertStanley@outlook.fr', '33' ,'Hebert', 'Stanley', 1, '46 Rue  des salades de fruits 92454', '1995-9-10', '3o8JG9${0JE+vC_XW9WH');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WhiteGriffith@yopmail.com', '34' ,'White', 'Griffith', 2, '37 Rue  du feu 92245', '1996-12-11', 'Y_pX2X_ObGJZI7Og}$9O');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('KendallEric@fictif.com', '35' ,'Kendall', 'Eric', 2, '4 Rue  du moulin 92116', '1990-8-15', '14_i9w)z54-dhMEG}nGV');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('RiveraHolcomb@oracle.com', '36' ,'Rivera', 'Holcomb', 1, '66 Rue  des fous 92326', '1977-4-13', '5Rei[[8VHacfR5ASmz]V');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('FrancisWhite@gmail.com', '37' ,'Francis', 'White', 1, '56 Rue  du moulin 92153', '1988-8-5', 'dv$VHjX5J{SyH9hX8F9K');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ChambersChambers@zumba.fr', '38' ,'Chambers', 'Chambers', 1, '78 Rue  de la poucave  92081', '1976-7-12', '4+_TI5qq%*WgbS+r[3(a');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DanielJolie@gmail.com', '39' ,'Daniel', 'Jolie', 1, '55 Rue  des fous 92184', '1984-10-12', 'G2cc4rVGOx91TpOv0gW{');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('FrancisMann@zakahev.ru', '40' ,'Francis', 'Mann', 1, '44 Rue  du moulin 92895', '1979-8-24', 'MGf*l_1pLeoHQLbQdB+h');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('NigelPittman@zumba.fr', '41' ,'Nigel', 'Pittman', 2, '65 Rue  du moulin 92357', '1998-8-23', '+P_o-(Of&peOzX31Xv!0');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ValenciaGraham@lefou.com', '42' ,'Valencia', 'Graham', 2, '38 Rue  de la fuerca 92132', '1999-5-28', '8z)VURhUlq-yo3BPk%9H');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('RossBolton@boomfaya.com', '43' ,'Ross', 'Bolton', 1, '38 Rue  de la fete 92085', '1985-8-27', 'p}8!cxZsU=+5p(x_tIOk');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WilliamValencia@cocorico.com', '44' ,'William', 'Valencia', 2, '63 Rue  du feu 92159', '1977-12-21', 'm=XIzWSDXnWRzR&wHimI');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BrownKato@toto.com', '45' ,'Brown', 'Kato', 2, '6 Rue  des temps 92020', '1978-1-14', 'Mo@1Dns)fAOXhn5E?ibV');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ZephaniaMedge@tacos.fr', '46' ,'Zephania', 'Medge', 1, '6 Rue  de la fete 92039', '1989-4-20', 'u3)q8M!I}[UR6Et*fi1$');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DustinHubbard@email.com', '47' ,'Dustin', 'Hubbard', 2, '28 Rue  des fous 92800', '1985-5-8', 'L0?Xdk@NvloYso@o_9$w');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('SantosPhelps@hotmail.fr', '48' ,'Santos', 'Phelps', 2, '28 Rue  des salades de fruits 92488', '1995-11-8', '!Cy%r@w-ib4(b@e8d1!*');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('OnealTucker@email.fr', '49' ,'Oneal', 'Tucker', 2, '57 Rue  des raclettes 92922', '1990-12-11', 'SBYimQg9YvzAlEH_f=l$');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('StanleyBarber@oracle.com', '50' ,'Stanley', 'Barber', 2, '96 Rue  du radin 92786', '1992-10-2', '1ui[*DHMJ]p]mRd6dMU!');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GordonBarron@reznov.ru', '51' ,'Gordon', 'Barron', 2, '44 Rue  des putois 92495', '1988-9-2', '=CTQ_exZ[wOeJHe$)?NR');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('RobertMatthew@reznov.ru', '52' ,'Robert', 'Matthew', 2, '82 Rue  des salades de fruits 92854', '1980-12-6', 'uSxnl%krJTlly+e=hmg3');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BasilKirk@lefou.com', '53' ,'Basil', 'Kirk', 1, '66 Rue  des temps 92562', '1976-1-10', 'E53W]!unMSWgnPA+SNvq');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BoltonBolton@cocorico.com', '54' ,'Bolton', 'Bolton', 1, '60 Rue  de la poucave  92800', '1993-12-25', 'TgnB0UbPP]&*9bpWNSgC');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CopelandPittman@lefou.com', '55' ,'Copeland', 'Pittman', 2, '39 Rue  des fous 92765', '1994-2-9', 'F3y]=EMPBjVrg@vWvr+S');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WilliamWhite@tacos.fr', '56' ,'William', 'White', 1, '91 Rue  des salades de fruits 92565', '1997-9-3', 'KnIhd7EF*O@rcQtRpO{}');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PetersenChancellor@oracle.com', '57' ,'Petersen', 'Chancellor', 1, '31 Rue  de la fuerca 92502', '1979-6-27', 'JZ(ASOebQhyhdKEC&KTw');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DanaHill@zakahev.ru', '58' ,'Dana', 'Hill', 1, '6 Rue  du moulin 92291', '1994-7-1', 'Uu(LLy5Fvl!sWyOoePBm');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ReidYeo@zizou.com', '59' ,'Reid', 'Yeo', 2, '80 Rue  des raclettes 92388', '1987-10-16', 'k[kb1S*no1RKficD-vW@');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('JolieDavis@zakahev.ru', '60' ,'Jolie', 'Davis', 1, '92 Rue  des temps 92925', '1981-7-2', '8%04Ny}@9Do3?Ip=Z7@&');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PriscillaWilliam@fictif.com', '61' ,'Priscilla', 'William', 1, '89 Rue  des temps 92955', '1993-8-10', '6hL}DqCXi!dPzs&bb?=f');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('MedgeCampos@zetrov.ru', '62' ,'Medge', 'Campos', 2, '67 Rue  de la poucave  92352', '1997-7-5', 'lguz7C{FUS2ZrZ(cQiVc');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DanaHannah@yopmail.com', '63' ,'Dana', 'Hannah', 2, '69 Rue  des salades de fruits 92270', '1977-10-9', '3bc{=998tUr{Rnc&CYJa');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PhelpsPeck@oracle.com', '64' ,'Phelps', 'Peck', 2, '96 Rue  des putois 92072', '1985-3-24', 'u742&[G{g!{0nFI28%28');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ZeldaTucker@netflix.com', '65' ,'Zelda', 'Tucker', 1, '90 Rue  de la fuerca 92312', '1987-3-6', '593cgs$Xfclhh0khdY&p');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('HannaWhite@tacos.fr', '66' ,'Hanna', 'White', 1, '84 Rue  du moulin 92065', '1977-2-11', '4nk0P@FZ_Xwp]MjcjnMZ');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('HermioneNell@zeratul.ru', '67' ,'Hermione', 'Nell', 2, '67 Rue  des temps 92366', '1997-2-20', '96$b-I9ce75_JPV-j3[j');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WillisLacota@yopmail.com', '68' ,'Willis', 'Lacota', 2, '47 Rue  des raclettes 92094', '1985-12-9', '&3(F70T$RcKb1QnCwnoL');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ContrerasPhyllis@tata.com', '69' ,'Contreras', 'Phyllis', 2, '29 Rue  de la poucave  92556', '1977-5-1', 'H@JY]gqC86?3UgVTF?s0');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('KeeganBarron@cocorico.com', '70' ,'Keegan', 'Barron', 2, '75 Rue  du feu 92078', '1980-4-22', 'dHY4]uX=lmtwakf}4jpL');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GermaneJoyner@email.com', '71' ,'Germane', 'Joyner', 1, '2 Rue  de la poucave  92763', '1996-11-6', '2n-!?ChAk)8KS[(d$g1C');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('MannBruce@bestmail.com', '72' ,'Mann', 'Bruce', 1, '51 Rue  des putois 92477', '1997-2-27', '6ytBOu5FKQ_VYtkPMU+S');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PalmerPhyllis@zizou.com', '73' ,'Palmer', 'Phyllis', 1, '61 Rue  des putois 92886', '1989-2-22', 'YjACmRX@Au&J&@*19AeB');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('JohnstonMaggie@supersayan.fr', '74' ,'Johnston', 'Maggie', 2, '5 Rue  du feu 92776', '1981-6-28', 'XiA8IuiZVnYeM0TYeFpJ');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GrahamBolton@tata.com', '75' ,'Graham', 'Bolton', 1, '53 Rue  de la fuerca 92998', '1986-10-28', 'U{ds6nPH!2i6sMN0]Xel');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('RileyGraham@bestmail.com', '76' ,'Riley', 'Graham', 2, '6 Rue  de la fete 92505', '1982-2-1', 'OAnnU(!m*BdCQbs=n4tj');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('JolieDustin@hotmail.fr', '77' ,'Jolie', 'Dustin', 2, '61 Rue  des raclettes 92256', '1994-3-22', 'F3)f{@?v?zW4s0v6re5I');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PhyllisChambers@cocorico.com', '78' ,'Phyllis', 'Chambers', 2, '23 Rue  des temps 92645', '1996-6-9', 'Njf[eYK9(v5=0S1M9GLo');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PalmerCantu@hotmail.fr', '79' ,'Palmer', 'Cantu', 1, '2 Rue  du radin 92120', '1982-9-22', 'FtaSt(ybO?elX}l@9g)i');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('AkeemFrancis@gmail.com', '80' ,'Akeem', 'Francis', 2, '8 Rue  des raclettes 92408', '1979-9-15', 'w[D*Vb8TGMVW$G1AyfR0');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CallumLacota@toto.com', '81' ,'Callum', 'Lacota', 1, '3 Rue  de la fete 92642', '1978-8-15', 'esRGwTmgTEQ8Br(vZzSC');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GrantHubbard@reznov.ru', '82' ,'Grant', 'Hubbard', 2, '30 Rue  du feu 92728', '1988-7-2', 'CnNxz(83WR6eT1XMOGz!');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DodsonChambers@lefou.com', '83' ,'Dodson', 'Chambers', 1, '35 Rue  des raclettes 92525', '1987-12-22', 'RYWKV*BChtb]Z{KDji!T');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('HubbardKendall@zetrov.ru', '84' ,'Hubbard', 'Kendall', 1, '50 Rue  de la poucave  92055', '1977-8-6', 'WZHAq{AyzxfgfGVDv@BY');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('WyattMcdonald@fictif.com', '85' ,'Wyatt', 'Mcdonald', 2, '32 Rue  de la fete 92237', '1980-10-20', 'nhfsFy-P][K-KN&5RGVH');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PhelpsLogan@zakahev.ru', '86' ,'Phelps', 'Logan', 2, '71 Rue  des raclettes 92423', '1997-12-12', ']UjWOm(]kHILVQp&ERXe');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BruceBranch@hotmail.fr', '87' ,'Bruce', 'Branch', 2, '36 Rue  du feu 92412', '1980-9-14', 'nyJbA4?kmf$yudX5sSZB');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DrakeWyatt@supersayan.fr', '88' ,'Drake', 'Wyatt', 1, '85 Rue  de la poucave  92983', '1999-6-21', 'k[*g7bokk5)BPMM4jJBy');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('SybilTucker@bestmail.com', '89' ,'Sybil', 'Tucker', 1, '66 Rue  des raclettes 92826', '1993-10-1', '@C01BTN$iS+p*8mRDaRd');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('OnealChambers@gmail.com', '90' ,'Oneal', 'Chambers', 2, '3 Rue  des putois 92712', '1982-9-6', ']MSjf(nI+mGh*%szLnN-');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('EstradaFlorence@yopmail.com', '91' ,'Estrada', 'Florence', 1, '45 Rue  du feu 92965', '1989-4-7', '}px]+0_Zv[i=0cs=B{fC');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('MelendezTasha@zakahev.ru', '92' ,'Melendez', 'Tasha', 1, '34 Rue  des temps 92535', '1998-4-18', '+@o)mL_x5I==J]uQ]F3D');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DustinElmo@zizou.com', '93' ,'Dustin', 'Elmo', 2, '56 Rue  des temps 92624', '1989-6-14', '9fI2c=2-es2igLWnx5T}');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('BarronJackson@outlook.fr', '94' ,'Barron', 'Jackson', 1, '12 Rue  de la poucave  92456', '1978-7-17', '9bcz!347jUEi6F4(F-T0');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('PittmanAlexander@gmail.com', '95' ,'Pittman', 'Alexander', 1, '47 Rue  du radin 92538', '1994-8-17', '4%hG2$_qEj]wVtW(?UST');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('ZephaniaPriscilla@supersayan.fr', '96' ,'Zephania', 'Priscilla', 1, '41 Rue  des raclettes 93000', '2000-10-21', 'A*tFa%2+9exp(YXQURVl');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('GlennaMaggie@cocorico.com', '97' ,'Glenna', 'Maggie', 1, '53 Rue  de la fuerca 92225', '2000-10-22', 'UMlgi3CM_4XRBTKy7rkd');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('IsadoraWillis@netflix.com', '98' ,'Isadora', 'Willis', 2, '18 Rue  de la poucave  92504', '1995-3-10', '@!xy+[8RYwW[0M*f=d0%');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('DustinGriffith@zeratul.ru', '99' ,'Dustin', 'Griffith', 2, '13 Rue  du feu 92333', '1991-5-4', '8aHw0*&[qi8REnE6ZjEP');
INSERT INTO clients (Email, Id_cl, Nom, Prenom, Sexe, Adresse, Dt, Mdp) VALUES ('CantuOwens@supersayan.fr', '100' ,'Cantu', 'Owens', 2, '76 Rue  du moulin 92803', '1993-6-21', 'yw6N1]BwM0za4+tnDGP[');

