version: '3.8'

services:
  novatechdatabase:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: reznov
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

    volumes:
      - ../src/main/resources/Images:/docker-entrypoint-initdb.d/Images
      - ./initScript/init.sh:/docker-entrypoint-initdb.d/1_init.sh
      - ./initScript/fillingData/1_createSchema.sql:/docker-entrypoint-initdb.d/1_createSchema.sql
      - ./initScript/fillingData/2_clientsInit.sql:/docker-entrypoint-initdb.d/2_clientsInit.sql
      - ./initScript/fillingData/3_produitsInit.sql:/docker-entrypoint-initdb.d/3_produitsInit.sql
      - ./initScript/fillingData/4_commandesInit.sql:/docker-entrypoint-initdb.d/4_commandesInit.sql
      - ./initScript/fillingData/5_detailsCommandesInit.sql:/docker-entrypoint-initdb.d/5_detailsCommandesInit.sql